In [1]:
 """f(x)=x1^2+x2^2+x3^2
lb=0, ub=8
size=6"""
import numpy as np
#Initialization of problem
size=6
n_e=size//2
pop=np.empty((n_e,3))

for i in range(pop.shape[0]):
    for j in range(pop.shape[1]):
        pop[i,j]=0+np.random.random((1,))*(8-0)
print(pop)

[[6.28538745 6.84266968 2.00937599]
 [0.84295056 1.77477986 2.34282649]
 [2.37919983 6.97788543 6.01834731]]


In [2]:
def objective(pop):
    f=[]
    for i in range(pop.shape[0]):
        f.append(pop[i,0]**2+pop[i,1]**2+pop[i,2]**2)
    return f

def fitness(pop):
    o=objective(pop)
    fit=[]
    for i in o:
        if(i<0):
            fit.append(1-i)
        else:
            fit.append(1/(1+i))
    return fit
best=pop[np.argmax(fitness(pop)),:]
trial=[0]*pop.shape[0]
print(pop)
print(fitness(pop))
print(best)
print(trial)


[[6.28538745 6.84266968 2.00937599]
 [0.84295056 1.77477986 2.34282649]
 [2.37919983 6.97788543 6.01834731]]
[0.010945012576027332, 0.09662540472139082, 0.010920370911254607]
[0.84295056 1.77477986 2.34282649]
[0, 0, 0]


In [3]:
#Employee bee's phase
import random
def employee(pop,fit,lb,up,trial,n_e):
    for i in range(3):
        p=random.randint(0,2)
        while(i==p):
            p=random.randint(0,2)
        j=random.randint(0,pop.shape[1]-1)
        new=pop[i,j]+np.random.uniform(low=-1,high=1,size=(1,))*(pop[i,j]-pop[p,j])
        if(new<lb):
            new=lb
        if(new>up):
            new=up
        x_new=np.array([pop[i,:].copy()])
        x_new[0,j]=new
        f=fitness(x_new)
        if(f>fit[i]):
            pop[i,:]=x_new[:]
            trial[i]=0
        else:
            trial[i]=trial[i]+1
    return pop

print(employee(pop,fitness(pop),0,8,trial,n_e))
print(trial)

[[6.28538745 6.84266968 2.00937599]
 [0.84295056 1.77477986 2.34282649]
 [2.37919983 6.97788543 2.37313683]]
[1, 1, 0]
